version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smart-wallet-postgres
    environment:
      POSTGRES_DB: smart_wallet_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: smart-wallet-redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: smart-wallet-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

volumes:
  postgres_data: