spring.application.name=smart-wallet

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_wallet
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}



# Server
server.port=8080
server.error.include-message=ALWAYS

# JWT Configurations (RS256 Asimetrik)
jwt.private-key-path=classpath:keys/private_key.pem
jwt.public-key-path=classpath:keys/public_key.pem
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=432000000

# IBAN Hibrit Şifreleme Anahtarları
encryption.private-key-path=classpath:keys/enc-private.pem
encryption.public-key-path=classpath:keys/enc-public.pem








